### ISSUE TITLE
utils.js crashes IE11 with 'Expected identifier, string or number'

### ISSUE THREAD

**Issue by robtree** [gtm-support/core#20]
## Info

| Tool    | Version       |
| ------- | ------------- |
| Package | @gtm-support/vue2-gtm v1.0.0 |
| Node    | v14.1.0        |
| OS      | win |

When running a production (Vue) build which uses https://www.npmjs.com/package/@gtm-support/vue2-gtm, the bundle fails to load in IE11 (screenshot below) due to a problem in utils.js from gtm-support/core.

![image](https://user-images.githubusercontent.com/3150192/121007798-22e85d80-c78a-11eb-9ccf-dc9da089748d.png)

**Comment by Shinigami92** [comment]
I don't have an environment to test against an IE11
Can you find more out about this problem? Also the code looks very "modern", with `const` and `...` spread operator and so on. Are these the sourcemaps or the finished source that gets executed in IE11, if second, then you may need to transpile it further down 🤔

**Comment by robtree** [comment]
The problematic part of the transpiled/finished source code looks like this:

`const u = new URLSearchParams({ id: t, ...(null !== (i = e.queryParams) && void 0 !== i ? i : {}) });`

Reverting to https://github.com/mib200/vue-gtm solves the problem, the same code in the loadScript function in https://github.com/mib200/vue-gtm/blob/master/src/utils.ts looks simpler.

**Comment by Shinigami92** [comment]
But https://github.com/gtm-support/core/blob/66b68c33261f7839c713411f5b172dc8de56e72a/src/utils.ts#L56-L59 and https://github.com/mib200/vue-gtm/blob/vue-2/src/utils.ts#L36-L39 are the same code

So it must be something with down transpiling 🤔 

---

Yes... 

https://github.com/mib200/vue-gtm/blob/73d39cf1e77dfb3ed0db02dc2ca04e1aedf5965d/tsconfig.json#L3
vs
https://github.com/gtm-support/core/blob/66b68c33261f7839c713411f5b172dc8de56e72a/tsconfig.json#L3

I think you have a bundler on your side, like webpack or so.
Is it possible to tell your bundler to transpile it further down?

Otherwise I need to look into how to ship multiple targets, so folks without IE11 have smaller bundler size and folks with IE11 needs to get served the old es5 code

**Comment by robtree** [comment]
Yes, I'm using Vue CLI and my package.json targets IE11:

`"browserslist": [
    "> 1%",
    "last 2 versions",
    "not dead"
  ]`

Now I can set up vue.config.js like this as well:

`module.exports = {
  transpileDependencies: [
    '@gtm-support/core'
  ]
};`

**Comment by Shinigami92** [comment]
Nice, so if this works, I can update `README.md`.
So everyone with the need to support IE11 or similar can use this workaround 🙂

**Comment by robtree** [comment]
Sure, for those using Vue CLI it seems good. Thanks for helping with this issue :)

https://cli.vuejs.org/config/#transpiledependencies

**Comment by Shinigami92** [comment]
Note was added to the readme

https://github.com/gtm-support/core/commit/55a44e921c75a21fa2b74700bf65ed7ae062bc9f
https://github.com/gtm-support/vue-gtm/commit/a7d935ffaa75fa21863979b9762d3b284bc53456
